version: '3'

services:
    postgres:
        container_name: pg_server
        image: postgres
        environment: 
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        networks:
            - todo_network
        ports:
            - "5432:5432"
        restart: always

    todo_app:
        container_name: app_server
        image: jayjoshua/todo_app:latest
        networks: 
            - todo_network
        ports: 
            - "3000:3000"
        restart: always

networks: 
    todo_network:
        driver: bridge

volumes:
    postgres:
    pgadmin:
    todo_app:
